runtime: python27
api_version: 1
threadsafe: true
service: post_it

handlers:
- url: /templates
  static_dir: templates.app

- url: /resources
  static_dir: resources
  
- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
