<<<<<<< HEAD
#application: cheerbytes-whatif
=======
application: cheerbyte
>>>>>>> 13928b45a5c3eb60b2673f77d1e8b0e96f88a333
runtime: python27
api_version: 1
threadsafe: true
#service: cheerbyte

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /templates
  static_dir: templates.app

- url: /resources
  static_dir: resources

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest

- name: webapp2
  version: "2.5.2"
